Research_paper_summariser_task:
  description: >
    You are given a research questions {research_question} and a research paper {document} 
    Your job is to determine if the research paper is relevant to the research question
    1. Identify if the research paper is relevant to the research question or potential to be relevant
    If relevant do the following:
    1. Check if the research paper is up to date
    2. Highlight the key points of the research paper including the research gap, research question, research objective, research methodology, research findings, research conclusion, research recommendations
    3. Identify the potential of incorporating the research paper into the research question
    4. Provide a score between 0 and 100 for the relevance of the research paper to the research question
    Make use of the ragging tools to retrieve
  expected_output: >
    A short list of doted points summarizing the key information extracted from the text. 
    including the research gap, research question, research objective, research methodology, research findings, research conclusion, research recommendations
    Highlight the potential of incorporating the research paper into the research question
    Provide a score between 0 and 100 for the relevance of the research paper to the research question