# fly.toml app configuration file generated for agent-services on 2025-05-27T13:37:09+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agent-services'
primary_region = 'syd'

[build]

[processes]
  app = '/app/.venv/bin/python app.py'
  worker = '/app/.venv/bin/python worker.py'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['worker']
