Research_paper_summariser_task:
  description: >
    You are given the area of research {area_of_research} with paper title {paper_title} given paper content {paper_content} with abstract {abstract}
    Your job is to extract the key information from the research paper.
    The key information includes:
    1. Problem statement - what the gap is the paper trying to fill
    2. Core hypothesis - what did they set out to test
    3. Methodology - what was the methodology used to test the hypothesis
    4. Key findings - what did they find
    5. Key insights - what did they learn
    6. Key implications - what are the implications of the findings
    7. Key recommendations - what are the recommendations for the future
    The ragging tool is available to retrieve information from the research paper.
  expected_output: >
    A short lists of key information extracted from the research paper.

Analogy_explainer_task:
  description: >
    You are given the key information from the research paper {paper_title} and the area of research {area_of_research}
    Your job is to explain complex concepts, jargons or methods retrieved from the research paper in a way that is easy to understand.
    The target audience is a general public and the content should be easy to understand.
    The ragging tool is available to retrieve information from the research paper.
  expected_output: >
    A lists of key information from the research paper in a way that is easy to understand.

Linkedin_post_writer_task:
  description: >
    You are given the key information from the research paper {paper_title} and the area of research {area_of_research}
    Your job is to write a linkedin post based on the research paper. To outreach to the general public on the innovation and impact of the research paper.
    Make sure the post is engaging and the intro is catchy.
    The ragging tool is available to retrieve information from the research paper.
  expected_output: >
    A linkedin post based on the research paper with maximum word of 500 words

   